### ISSUE TITLE
Address usage instead of coordinates

### ISSUE THREAD

**Issue by ste990** [laki944/react-native-navigation-directions#18]
Hi Laki,

This works really well, thanks for sharing the code.

I am pulling locations from a json file, i have the address for the location but not the coordinates.

I am thinking about forking this off to see if I can make some changes to allow the endpoint to take either coordinate or address. Wondering if you attempted this and hit any issues?

I am thinking 1 issue may be a difference in formatting for the url between apple and google maps.

**Comment by laki944** [comment]
Hi @ste990, 

I didn't try to make it work with addresses, but I will be happy to merge your PR. 🍺 

> I am thinking 1 issue may be a difference in formatting for the url between apple and google maps.

I think this is not an issue because the code already split URL based on the platform.
https://github.com/laki944/react-native-navigation-directions/blob/afeb9d9db644b7cabd4c16cbfcd38da22ccc694d/index.js#L15

**Comment by ste990** [comment]
Got a work in progress in my fork.  

I am a bit wary that the validation for address isn't enough, if someone uses both coordinates and address it will break rather than throw an error. Working perfectly with my json lookup though.

Let you know when i come up with something a bit better, feel free to have a look and give me your opinion. 

I'm very new at this so feel free to point out any rookie mistakes :)
